const express = require('express');
const controllers = require('../controllers/controllers');
const  router = express.Router();

router.post('/albums',controllers.getAlbums);
router.post('/artistes', controllers.getArtistes);
router.post('/chansons', controllers.getChansons);
router.post('/inscrireUtilisateur', controllers.registerUser);
router.post('/connexionUtilisateur', controllers.userAuthentication);
router.post('/genreMusical', controllers.getMusicalGenre);
router.post('/albumGenre', controllers.getAlbumsByGenre);
router.post('/ajouterFavoris', controllers.addFavorite);
router.post('/supprimerFavoris', controllers.deleteFavorite);
router.post('/favorisUtilisateur', controllers.getFavoritesByUser);
router.post('/ajouterPanier', controllers.addCart);
router.post('/supprimerPanier', controllers.deleteAlbumFromCart);
router.post('/panierUtilisateur', controllers.getCartByUser);
router.post('/informationUtilisateur', controllers.getUserInformation);
router.post('/totalPanier', controllers.getCartPrice);
router.post('/chansonsAlbum', controllers.getMusicByAlbum);
router.post('/ajouterCommandes', controllers.addPurchase);
router.post('/albumsCommandes', controllers.getAlbumsByPurchase);
router.post('/rechercheAlbum', controllers.getAlbumBySearch);
router.post('/rechercheParPrix', controllers.getAlbumByPrice);
router.post('/modifierQuantiteAlbum', controllers.modifyQuantityAlbum);
router.post('/ajouterAlbum', controllers.addAlbum);
router.post('/supprimerAlbum', controllers.removeAlbum);
router.post('/commandesEnAttente', controllers.getOrderPending);
router.post('/commandesValidee', controllers.getOrderValidated);
router.post('/commandesExpediee', controllers.getOrderShipped);
router.post('/commandesLivree', controllers.getOrderDelivered);
router.post('/modifierStatut', controllers.modifyStatus);
router.post('/commandesUtilisateur', controllers.getOrderByUser);
router.post('/search', controllers.searchAlgolia);
module.exports = router;
