const express = require('express');
const controllers = require('../controllers/controllers');
const  router = express.Router();

router.get('/albums',controllers.getAlbums);
router.get('/artistes', controllers.getArtistes);
router.get('/chansons', controllers.getChansons);
router.get('/inscrireUtilisateur', controllers.registerUser);
router.get('/connexionUtilisateur', controllers.userAuthentication);
router.get('/genreMusical', controllers.getMusicalGenre);
router.get('/albumGenre', controllers.getAlbumsByGenre);
router.get('/ajouterFavoris', controllers.addFavorite);
router.get('/supprimerFavoris', controllers.deleteFavorite);
router.get('/favorisUtilisateur', controllers.getFavoritesByUser);
router.get('/ajouterPanier', controllers.addCart);
router.get('/supprimerPanier', controllers.deleteAlbumFromCart);
router.get('/panierUtilisateur', controllers.getCartByUser);
router.get('/informationUtilisateur', controllers.getUserInformation);
router.get('/totalPanier', controllers.getCartPrice);
router.get('/chansonsAlbum', controllers.getMusicByAlbum);
router.get('/ajouterCommandes', controllers.addPurchase);
router.get('/albumsCommandes', controllers.getAlbumsByPurchase);
router.get('/rechercheAlbum', controllers.getAlbumBySearch);
router.get('/rechercheParPrix', controllers.getAlbumByPrice);
router.get('/modifierQuantiteAlbum', controllers.modifyQuantityAlbum);
router.get('/ajouterAlbum', controllers.addAlbum);
router.get('/supprimerAlbum', controllers.removeAlbum);
router.get('/commandesEnAttente', controllers.getOrderPending);
router.get('/commandesValidee', controllers.getOrderValidated);
router.get('/commandesExpediee', controllers.getOrderShipped);
router.get('/commandesLivree', controllers.getOrderDelivered);
router.get('/modifierStatut', controllers.modifyStatus);
router.get('/commandesUtilisateur', controllers.getOrderByUser);

module.exports = router;